lst_second_item = ['#!/accessories/head', '#!/accessories/face', '#!/accessories/neck', 
'#!/accessories/shoulder', '#!/accessories/front', '#!/accessories/back', 
'#!/accessories/waist', '#!/accessories/gear', '#!/animations/animations', 
'#!/audio/audio', '#!/avatar-animations/run', '#!/avatar-animations/walk', 
'#!/avatar-animations/fall', '#!/avatar-animations/jump', '#!/avatar-animations/idle', 
'#!/avatar-animations/swim', '#!/avatar-animations/climb', '#!/badges/badges', 
'#!/bottoms/pants', '#!/bottoms/shorts', '#!/bottoms/skirts', 
'#!/bundles/body-parts', '#!/classic-clothing/classic-t-shirts', '#!/classic-clothing/classic-shirts', 
'#!/classic-clothing/classic-pants', '#!/classic-head/classic-heads', '#!/decals/decals', 
'#!/emote-animations/emotes', '#!/faces/faces', '#!/hair-accessories/hair', '#!/head/heads', 
'#!/meshparts/meshes', '#!/models/models', '#!/game-passes/passes', '#!/places/created-by-me', 
'#!/places/purchased', '#!/places/my-experiences', '#!/places/other-experiences', '#!/plugins/plugins', 
'#!/private-servers/my-private-servers', '#!/private-servers/other-private-servers', 
'#!/shoes/left-shoe', '#!/shoes/right-shoe', '#!/tops/t-shirts', '#!/tops/shirts', 
'#!/tops/sweaters', '#!/tops/jackets', '#!/video/video']